# Neural Network using Cancer Datatset

In [1]:
import torch
import numpy as np
import pandas as pd
from torch.autograd import Variable
import torch.nn.functional as F
from sklearn.preprocessing import LabelBinarizer, LabelEncoder
import os

In [3]:
data = pd.read_csv('/content/sample_data/data.csv')
data.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [4]:
data.shape

(569, 33)

### Preparing Dataset for training

In [6]:
cols = data.columns
x_data = data[cols[2:-1]]
x_data.head()

radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
0        17.99         10.38  ...          0.4601                  0.11890
1        20.57         17.77  ...          0.2750                  0.08902
2        19.69         21.25  ...          0.3613                  0.08758
3        11.42         20.38  ...          0.6638                  0.17300
4        20.29         14.34  ...          0.2364                  0.07678

[5 rows x 30 columns]

In [7]:
y_data = data[cols[1]]
le = LabelEncoder()
y_data = np.array(le.fit_transform(y_data))
print(y_data[:10])
print(le.classes_)

[1 1 1 1 1 1 1 1 1 1]
['B' 'M']


### Wrapping Dataset in type Variable

In [8]:
x_data = Variable(torch.from_numpy(x_data.values))
y_data = Variable(torch.from_numpy(y_data))

### Architecture

In [9]:
class Model(torch.nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.l1 = torch.nn.Linear(30,16)
        self.l2 = torch.nn.Linear(16,4)
        self.l3 = torch.nn.Linear(4,1)
        
        self.sigmoid = torch.nn.Sigmoid()
        
    def forward(self, x):
        out1 = self.sigmoid(self.l1(x)) 
        out2 = self.sigmoid(self.l2(out1))
        y_pred = self.sigmoid(self.l3(out2))
        return y_pred
    
model = Model()

### Training of the Neural Network

In [10]:
criterion = torch.nn.BCELoss(reduction='sum')
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

for epochs in range(400):
    y_pred = model(x_data.float())
    loss = criterion(y_pred, y_data.view(-1,1).float())
    print('Epoch',epochs,'Loss:',loss.item(), '- Pred:', y_pred.data[0])
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

Epoch 0 Loss: 377.9447021484375 - Pred: tensor([0.4017])
Epoch 1 Loss: 377.6399230957031 - Pred: tensor([0.4006])
Epoch 2 Loss: 377.3100891113281 - Pred: tensor([0.3995])
Epoch 3 Loss: 376.8821105957031 - Pred: tensor([0.3985])
Epoch 4 Loss: 376.5229187011719 - Pred: tensor([0.3974])
Epoch 5 Loss: 376.3439025878906 - Pred: tensor([0.3964])
Epoch 6 Loss: 376.28497314453125 - Pred: tensor([0.3953])
Epoch 7 Loss: 376.25042724609375 - Pred: tensor([0.3943])
Epoch 8 Loss: 376.2111511230469 - Pred: tensor([0.3933])
Epoch 9 Loss: 376.1658630371094 - Pred: tensor([0.3922])
Epoch 10 Loss: 376.12017822265625 - Pred: tensor([0.3912])
Epoch 11 Loss: 376.0765686035156 - Pred: tensor([0.3902])
Epoch 12 Loss: 376.03558349609375 - Pred: tensor([0.3892])
Epoch 13 Loss: 375.9974670410156 - Pred: tensor([0.3882])
Epoch 14 Loss: 375.96240234375 - Pred: tensor([0.3873])
Epoch 15 Loss: 375.9313049316406 - Pred: tensor([0.3863])
Epoch 16 Loss: 375.90521240234375 - Pred: tensor([0.3854])
Epoch 17 Loss: 375.88

In [11]:
x_data.data[0]

tensor([1.7990e+01, 1.0380e+01, 1.2280e+02, 1.0010e+03, 1.1840e-01, 2.7760e-01,
        3.0010e-01, 1.4710e-01, 2.4190e-01, 7.8710e-02, 1.0950e+00, 9.0530e-01,
        8.5890e+00, 1.5340e+02, 6.3990e-03, 4.9040e-02, 5.3730e-02, 1.5870e-02,
        3.0030e-02, 6.1930e-03, 2.5380e+01, 1.7330e+01, 1.8460e+02, 2.0190e+03,
        1.6220e-01, 6.6560e-01, 7.1190e-01, 2.6540e-01, 4.6010e-01, 1.1890e-01],
       dtype=torch.float64)

In [12]:
y_pred.data.shape

torch.Size([569, 1])

In [13]:
pred=model.double().forward(x_data) > 0.5

In [14]:
pred.numpy()[:5]

array([[ True],
       [ True],
       [ True],
       [False],
       [ True]])

In [15]:
a = pred.numpy()
b = y_data.numpy()
pred.numpy().reshape(-1).shape, y_data.numpy().shape

((569,), (569,))

### Results

In [16]:
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import plot_confusion_matrix
import matplotlib.pyplot as plt

c = confusion_matrix(a,b)
print(c)

[[352  35]
 [  5 177]]


In [17]:
print(classification_report(a,b))

              precision    recall  f1-score   support

       False       0.99      0.91      0.95       387
        True       0.83      0.97      0.90       182

    accuracy                           0.93       569
   macro avg       0.91      0.94      0.92       569
weighted avg       0.94      0.93      0.93       569

